config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  scope module: :web do
    root 'home#index'

    post 'auth/:provider', to: 'auth#request', as: :auth_request
    get 'auth/:provider/callback', to: 'auth#callback', as: :callback_auth
    delete 'auth/logout', to: 'auth#logout'

    resources :repositories, only: %i[index show new create] do
      scope module: :repositories do
        resources :checks, only: %i[create show]
      end
    end
  end

  namespace :api do
    resource :checks, only: :create
  end

  get 'up' => 'rails/health#show', as: :rails_health_check
end

app/models/repository.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: repositories
#
#  id         :integer          not null, primary key
#  name       :string
#  github_id  :integer          not null
#  full_name  :string
#  language   :string
#  clone_url  :string
#  ssh_url    :string
#  user_id    :integer          not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class Repository < ApplicationRecord
  extend Enumerize

  belongs_to :user
  has_many :checks, dependent: :destroy

  enumerize :language, in: %i[ruby javascript]

  validates :github_id, presence: true, uniqueness: true

  scope :latest, -> { order(created_at: :desc) }
end

app/models/repository/check.rb
# frozen_string_literal: true

class Repository::Check < ApplicationRecord
  include AASM

  belongs_to :repository
  has_many :files, dependent: :destroy
  has_many :problems, dependent: :destroy

  aasm column: :aasm_state do
    state :created, initial: true
    state :in_progress, :finished, :failed

    event :start do
      transitions from: :created, to: :in_progress
    end

    event :finish do
      transitions from: :in_progress, to: :finished
    end

    event :fail do
      transitions from: :in_progress, to: :failed
    end
  end

  scope :latest, -> { order(created_at: :desc) }
end

app/models/repository/check/file.rb
# frozen_string_literal: true

class Repository::Check::File < ApplicationRecord
  belongs_to :check
  has_many :problems, dependent: nil
end

app/models/repository/check/problem.rb
# frozen_string_literal: true

class Repository::Check::Problem < ApplicationRecord
  belongs_to :check
  belongs_to :file
end

app/controllers/web/repositories/application_controller.rb
# frozen_string_literal: true

module Web
  module Repositories
    class ApplicationController < ApplicationController
      before_action :authenticate_user!

      def resource_repository
        @resource_repository ||= Repository.find params[:repository_id]
      end
    end
  end
end

app/controllers/web/repositories/checks_controller.rb
# frozen_string_literal: true

module Web
  module Repositories
    class ChecksController < ApplicationController
      before_action :set_cached_check, only: :show
      def show
        authorize @check
      end

      def create
        @check = resource_repository.checks.build

        authorize @check

        if @check.save
          CheckReposJob.perform_later(@check.id)

          redirect_to repository_path(resource_repository), notice: t('.success')
        else
          redirect_to repository_path(resource_repository), notice: t('.fail')
        end
      end

      def set_cached_check
        @check = Rails.cache.fetch("#{params[:id]}/check", expires_in: 1.day) do
          resource_repository.checks.includes(%i[files problems]).find_by(id: params[:id])
        end
      end
    end
  end
end

app/controllers/web/repositories_controller.rb
# frozen_string_literal: true

module Web
  class RepositoriesController < ApplicationController
    before_action :authenticate_user!, only: %i[index show new create]
    before_action :set_cached_repos, only: :new

    def index
      @repositories = current_user.repositories
    end

    def show
      @repository = current_user.repositories.find(params[:id])
    end

    def new
      @repository = current_user.repositories.build
    end

    def create
      @repository = current_user.repositories.find_or_initialize_by(repository_params)

      authorize @repository

      if @repository.save
        redirect_to repositories_path, notice: t('.success')
        LoadReposJob.perform_later(@repository.id)
      else
        flash.now['alert'] = t('.fail')
        render :new, status: :unprocessable_entity
      end
    end

    private

    def repository_params
      params.require(:repository).permit(:github_id)
    end

    def set_cached_repos
      @users_repos = Rails.cache.fetch("#{current_user.id}/repos", expires_in: 15.minutes) do
        GithubClient.fetch_available_user_repos(current_user)
      end
    end
  end
end

app/helpers/web/repositories/checks_helper.rb
# frozen_string_literal: true

module Web::Repositories::ChecksHelper
  def link_to_github_commit(check, options = {})
    check.commit_id ? link_to(check.commit_id, build_commit_url(check), options.merge(target: :blank)) : ''
  end

  def link_to_github_file(check, path, options = {})
    check.commit_id ? link_to(path, build_path_url(check, path), options.merge(target: :blank)) : ''
  end

  def build_commit_url(check)
    [check.repository.html_url, 'commit', check.commit_id].join('/')
  end

  def build_path_url(check, path)
    [check.repository.html_url, 'tree', check.commit_id, path].join('/')
  end
end

app/helpers/web/repositories_helper.rb
# frozen_string_literal: true

module Web::RepositoriesHelper
end

app/views/web/repositories/_form.html.slim
.container.px-0.mt-4.mb-5.pb-5#home
  .card.shadow.p-4
    = simple_form_for @repository do |f|
      .form-inputs
        = f.input :github_id, collection: @users_repos,
        label_method: :name, value_method: :id
      .form-actions
        = f.button :submit, class: 'btn btn-success'

app/views/web/repositories/index.html.slim
.container.px-0.mt-4.mb-5.pb-5#repositories
  .card.shadow.p-4
    .d-flex.align-items-start
      = link_to t('.new'), new_repository_path, { class: 'btn btn-primary mb-4' }
    table.table.table-striped.table-hover.mt-4
      thead
        tr
          th = Repository.human_attribute_name(:name)
          th = Repository.human_attribute_name(:language)
          th = t('.last_check_status')
      tbody
        - @repositories.latest.each do |repository|
          tr
            - if repository.name
              td = link_to repository.name, repository_path(repository)
            - else
              td = link_to '-', repository_path(repository)
            td = repository.language
            - if repository.checks.count.zero?
              td = t('.check_is_not_started')
            - elsif repository.checks.last&.passed.nil?
              td = '-'
            - else
              td = t(repository.checks.last&.passed?)

app/views/web/repositories/new.html.slim
= render 'form'

app/views/web/repositories/show.html.slim
.container.px-0.mt-4.mb-5.pb-5#repositories
  .card.shadow.p-4
    h1.mb-4 = @repository.full_name

    .d-flex.align-items-start
      = link_to t('.check'),
      repository_checks_path(@repository), class: 'btn btn-primary mb-4', data: { turbo_method: :post }

    p
      span
        strong.me-2 = Repository.human_attribute_name(:name)
        = @repository.full_name
    p
      span
        strong.me-2 = Repository.human_attribute_name(:language)
        = @repository.language
    p
      span
        strong.me-2 = Repository.human_attribute_name(:created_at)
        = l(@repository.created_at, format: :long)
    p
      span
        strong.me-2 = Repository.human_attribute_name(:updated_at)
        = l(@repository.updated_at, format: :long)

    table.table.table-striped.table-hover.mt-4
      thead
        tr
          th{ scope = 'col' }
          th = Repository::Check.human_attribute_name(:aasm_state)
          th = Repository::Check.human_attribute_name(:commit_id)
          th = Repository::Check.human_attribute_name(:passed)
          th = Repository::Check.human_attribute_name(:created_at)
      tbody
        - @repository.checks.latest.each do |check|
            tr
              td = link_to check.id, repository_check_path(@repository, check)
              td = localized_check_state(check.aasm.human_state)
              td = link_to_github_commit(check)
              - if check.passed.nil?
                td = '-'
              - else
                td = t(check.passed?)
              td = l(check.created_at, format: :long)