config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  scope module: :web do
    root 'home#index'

    post 'auth/:provider', to: 'auth#request', as: :auth_request
    get 'auth/:provider/callback', to: 'auth#callback', as: :callback_auth
    delete 'auth/logout', to: 'auth#logout'

    resources :repositories, only: %i[index show new create] do
      scope module: :repositories do
        resources :checks, only: %i[create show]
      end
    end
  end

  namespace :api do
    resource :checks, only: :create
  end

  get 'up' => 'rails/health#show', as: :rails_health_check
end

app/views/layouts/_flash.html.slim
- if flash[:notice]
 .container.mb-2.d-flex.flex-wrap.alert.alert-info
    = flash[:notice]

- if flash[:alert]
 .container.mb-2.d-flex.flex-wrap.alert.alert-danger
    = flash[:alert]

- if flash[:success]
 .container.mb-2.d-flex.flex-wrap.alert.alert-success
    = flash[:success]

- if flash[:warning]
 .container.mb-2.d-flex.flex-wrap.alert.alert-warning
    = flash[:warning]

- if flash[:error]
 .container.mb-2.d-flex.flex-wrap.alert.alert-danger
    = flash[:error]

app/views/layouts/application.html.slim
doctype html
html
  head
    title "Hexlet Quality"
    meta name="viewport" content="width=device-width,initial-scale=1"
    = csrf_meta_tags
    = csp_meta_tag

    = stylesheet_link_tag 'application', 'data-turbo-track': 'reload'
    = javascript_include_tag 'application', 'data-turbo-track': 'reload', type: 'module'
  body
    .container.mb-2.px-0.d-flex.flex-wrap.align-items-center.py-2.border-bottom
      .navbar.navbar-expand-md.navbar-light.me-auto
        = link_to t('navbar.home'), root_path, { class: 'nav-link link-dark me-2' }
        - if signed_in?
          = link_to t('navbar.repos'), repositories_path, { class: 'nav-link link-dark me-2' }
      .nav.nav-pills
        - unless signed_in?
          div(title="#{t('navbar.login')}")
            = form_with url: auth_request_path(:github), data: { turbo: 'false' } do |f|
              = f.button class: 'nav-link link-dark' do
                i.bi.bi-github
        - if signed_in?
          = link_to current_user.email, root_path, { class: 'nav-link link-secondary' }
          div(title="#{t('navbar.logout')}")
            = link_to auth_logout_path, { class: 'nav-link link-dark', data: { turbo_method: :delete } } do
              i.bi.bi-door-open

    - flash.each do
      = render 'layouts/flash'

    = yield

    footer.container.d-flex.flex-wrap.justify-content-between.align-items-center.py-3.my-4.border-top
      p.col-md-4.mb-0.text-body-secondary
        = "© #{Time.zone.today.year} Hexlet"